//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Reference to a database
 * 
 * <p>Java class for DatabaseReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatabaseReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://bioxsd.org/BioXSD-1.1}WebserviceReference"/>
 *       &lt;attribute name="dbName" type="{http://bioxsd.org/BioXSD-1.1}DatabaseName" />
 *       &lt;attribute name="dbUri" type="{http://bioxsd.org/BioXSD-1.1}Uri" />
 *       &lt;attribute name="dbVersion" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *       &lt;attribute name="localCopyOfDb" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatabaseReference")
@XmlSeeAlso({
    ncbisegout.FeatureRecord.BlockWithOccurrenceReferences.Database.class,
    EntryReference.class
})
public class DatabaseReference {

    @XmlAttribute(name = "dbName")
    protected String dbName;
    @XmlAttribute(name = "dbUri")
    protected String dbUri;
    @XmlAttribute(name = "dbVersion")
    protected String dbVersion;
    @XmlAttribute(name = "localCopyOfDb")
    protected Boolean localCopyOfDb;
    @XmlAttribute(name = "wsdl")
    protected String wsdl;
    @XmlAttribute(name = "wsdlService")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String wsdlService;
    @XmlAttribute(name = "wsdlPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String wsdlPort;
    @XmlAttribute(name = "webserviceOperation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String webserviceOperation;
    @XmlAttribute(name = "webserviceVersion")
    protected String webserviceVersion;
    @XmlAttribute(name = "webserviceDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar webserviceDate;

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the dbUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbUri() {
        return dbUri;
    }

    /**
     * Sets the value of the dbUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbUri(String value) {
        this.dbUri = value;
    }

    /**
     * Gets the value of the dbVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbVersion() {
        return dbVersion;
    }

    /**
     * Sets the value of the dbVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbVersion(String value) {
        this.dbVersion = value;
    }

    /**
     * Gets the value of the localCopyOfDb property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLocalCopyOfDb() {
        if (localCopyOfDb == null) {
            return false;
        } else {
            return localCopyOfDb;
        }
    }

    /**
     * Sets the value of the localCopyOfDb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalCopyOfDb(Boolean value) {
        this.localCopyOfDb = value;
    }

    /**
     * Gets the value of the wsdl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdl() {
        return wsdl;
    }

    /**
     * Sets the value of the wsdl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdl(String value) {
        this.wsdl = value;
    }

    /**
     * Gets the value of the wsdlService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdlService() {
        return wsdlService;
    }

    /**
     * Sets the value of the wsdlService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdlService(String value) {
        this.wsdlService = value;
    }

    /**
     * Gets the value of the wsdlPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdlPort() {
        return wsdlPort;
    }

    /**
     * Sets the value of the wsdlPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdlPort(String value) {
        this.wsdlPort = value;
    }

    /**
     * Gets the value of the webserviceOperation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebserviceOperation() {
        return webserviceOperation;
    }

    /**
     * Sets the value of the webserviceOperation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebserviceOperation(String value) {
        this.webserviceOperation = value;
    }

    /**
     * Gets the value of the webserviceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebserviceVersion() {
        return webserviceVersion;
    }

    /**
     * Sets the value of the webserviceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebserviceVersion(String value) {
        this.webserviceVersion = value;
    }

    /**
     * Gets the value of the webserviceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWebserviceDate() {
        return webserviceDate;
    }

    /**
     * Sets the value of the webserviceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWebserviceDate(XMLGregorianCalendar value) {
        this.webserviceDate = value;
    }

}
