//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Reference to an entry in a database
 * 
 * <p>Java class for EntryReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntryReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}DatabaseReference">
 *       &lt;attribute name="accession" type="{http://bioxsd.org/BioXSD-1.1}Accession" />
 *       &lt;attribute name="entryUri" type="{http://bioxsd.org/BioXSD-1.1}Uri" />
 *       &lt;attribute name="entryVersion" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntryReference")
@XmlSeeAlso({
    SequenceReference.class,
    Species.class
})
public class EntryReference
    extends DatabaseReference
{

    @XmlAttribute(name = "accession")
    protected String accession;
    @XmlAttribute(name = "entryUri")
    protected String entryUri;
    @XmlAttribute(name = "entryVersion")
    protected String entryVersion;
    @XmlAttribute(name = "date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the entryUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryUri() {
        return entryUri;
    }

    /**
     * Sets the value of the entryUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryUri(String value) {
        this.entryUri = value;
    }

    /**
     * Gets the value of the entryVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryVersion() {
        return entryVersion;
    }

    /**
     * Sets the value of the entryVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryVersion(String value) {
        this.entryVersion = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

}
