//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Evidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Evidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="predicted" type="{http://bioxsd.org/BioXSD-1.1}PredictionResult"/>
 *         &lt;element name="experimental" type="{http://bioxsd.org/BioXSD-1.1}ExperimentalEvidence"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Evidence", propOrder = {
    "predicted",
    "experimental"
})
public class Evidence {

    protected PredictionResult predicted;
    protected ExperimentalEvidence experimental;

    /**
     * Gets the value of the predicted property.
     * 
     * @return
     *     possible object is
     *     {@link PredictionResult }
     *     
     */
    public PredictionResult getPredicted() {
        return predicted;
    }

    /**
     * Sets the value of the predicted property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredictionResult }
     *     
     */
    public void setPredicted(PredictionResult value) {
        this.predicted = value;
    }

    /**
     * Gets the value of the experimental property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentalEvidence }
     *     
     */
    public ExperimentalEvidence getExperimental() {
        return experimental;
    }

    /**
     * Sets the value of the experimental property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentalEvidence }
     *     
     */
    public void setExperimental(ExperimentalEvidence value) {
        this.experimental = value;
    }

}
