//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExperimentalEvidence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExperimentalEvidence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dataReference" type="{http://bioxsd.org/BioXSD-1.1}EntryReference"/>
 *         &lt;element name="citation" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="verdict" type="{http://bioxsd.org/BioXSD-1.1}Verdict" minOccurs="0"/>
 *         &lt;element name="reliability" type="{http://bioxsd.org/BioXSD-1.1}Reliability" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExperimentalEvidence", propOrder = {
    "dataReference",
    "citation",
    "verdict",
    "reliability"
})
public class ExperimentalEvidence {

    @XmlElement(required = true)
    protected EntryReference dataReference;
    protected List<EntryReference> citation;
    protected String verdict;
    protected String reliability;

    /**
     * Gets the value of the dataReference property.
     * 
     * @return
     *     possible object is
     *     {@link EntryReference }
     *     
     */
    public EntryReference getDataReference() {
        return dataReference;
    }

    /**
     * Sets the value of the dataReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryReference }
     *     
     */
    public void setDataReference(EntryReference value) {
        this.dataReference = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntryReference }
     * 
     * 
     */
    public List<EntryReference> getCitation() {
        if (citation == null) {
            citation = new ArrayList<EntryReference>();
        }
        return this.citation;
    }

    /**
     * Gets the value of the verdict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerdict() {
        return verdict;
    }

    /**
     * Sets the value of the verdict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerdict(String value) {
        this.verdict = value;
    }

    /**
     * Gets the value of the reliability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReliability() {
        return reliability;
    }

    /**
     * Sets the value of the reliability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReliability(String value) {
        this.reliability = value;
    }

}
