//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QualitativeCertainty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QualitativeCertainty">
 *   &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}Name">
 *     &lt;enumeration value="Certain"/>
 *     &lt;enumeration value="Uncertain"/>
 *     &lt;enumeration value="Value unknown"/>
 *     &lt;enumeration value="Certainly greater or equal"/>
 *     &lt;enumeration value="Certainly less or equal"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QualitativeCertainty")
@XmlEnum
public enum QualitativeCertainty {

    @XmlEnumValue("Certain")
    CERTAIN("Certain"),
    @XmlEnumValue("Uncertain")
    UNCERTAIN("Uncertain"),

    /**
     * The reffered value completely unknown, not the certainty unknown
     * 
     */
    @XmlEnumValue("Value unknown")
    VALUE_UNKNOWN("Value unknown"),
    @XmlEnumValue("Certainly greater or equal")
    CERTAINLY_GREATER_OR_EQUAL("Certainly greater or equal"),
    @XmlEnumValue("Certainly less or equal")
    CERTAINLY_LESS_OR_EQUAL("Certainly less or equal");
    private final String value;

    QualitativeCertainty(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualitativeCertainty fromValue(String v) {
        for (QualitativeCertainty c: QualitativeCertainty.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
