//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.15 at 10:06:18 PM CEST 
//


package ncbisegout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Formal reference to a sequence in a database or an explicit super-sequence
 * 
 * <p>Java class for SequenceReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SequenceReference">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}EntryReference">
 *       &lt;sequence>
 *         &lt;element name="subsequencePosition" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *         &lt;element name="supersequence" type="{http://bioxsd.org/BioXSD-1.1}Biosequence" minOccurs="0"/>
 *         &lt;element name="supersequenceName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sequenceVersion" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *       &lt;attribute name="variantAccession" type="{http://bioxsd.org/BioXSD-1.1}Accession" />
 *       &lt;attribute name="variantNote" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SequenceReference", propOrder = {
    "subsequencePosition",
    "supersequence",
    "supersequenceName"
})
public class SequenceReference
    extends EntryReference
{

    protected SequencePosition subsequencePosition;
    protected String supersequence;
    protected String supersequenceName;
    @XmlAttribute(name = "sequenceVersion")
    protected String sequenceVersion;
    @XmlAttribute(name = "variantAccession")
    protected String variantAccession;
    @XmlAttribute(name = "variantNote")
    protected String variantNote;

    /**
     * Gets the value of the subsequencePosition property.
     * 
     * @return
     *     possible object is
     *     {@link SequencePosition }
     *     
     */
    public SequencePosition getSubsequencePosition() {
        return subsequencePosition;
    }

    /**
     * Sets the value of the subsequencePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencePosition }
     *     
     */
    public void setSubsequencePosition(SequencePosition value) {
        this.subsequencePosition = value;
    }

    /**
     * Gets the value of the supersequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersequence() {
        return supersequence;
    }

    /**
     * Sets the value of the supersequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersequence(String value) {
        this.supersequence = value;
    }

    /**
     * Gets the value of the supersequenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersequenceName() {
        return supersequenceName;
    }

    /**
     * Sets the value of the supersequenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersequenceName(String value) {
        this.supersequenceName = value;
    }

    /**
     * Gets the value of the sequenceVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceVersion() {
        return sequenceVersion;
    }

    /**
     * Sets the value of the sequenceVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceVersion(String value) {
        this.sequenceVersion = value;
    }

    /**
     * Gets the value of the variantAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantAccession() {
        return variantAccession;
    }

    /**
     * Sets the value of the variantAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantAccession(String value) {
        this.variantAccession = value;
    }

    /**
     * Gets the value of the variantNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantNote() {
        return variantNote;
    }

    /**
     * Sets the value of the variantNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantNote(String value) {
        this.variantNote = value;
    }

}
