.TH BIOXSDCONV 1 LOCAL 

.SH NAME 

bioxsdconv - print "bioxsdconv world" on stdout 

.SH SYNOPSIS 

.B bioxsdconv [options] 

.I option option 

.B [" 

.I -yy -zz 

.B ..."] 

.SH AVAILABILITY 

All UNIX flavors 

.SH DESCRIPTION 

bioxsdconv prints the string "bioxsdconv world" on standard output. 

.SH OPTIONS 

There are no options, but we'll make some up. 

.TP 5 

-yy 

is one option 

.TP 

-zz 

is another option 

.SH AUTHOR 

U. R. Friendly
