.TH PROFISISXSD 1 LOCAL 

.SH NAME 

profisisxsd - bioxsd output converter for profisis

.SH SYNOPSIS 

.B profisisxsd profisis_output_file

.SH AVAILABILITY 

All UNIX flavors 

.SH DESCRIPTION 

profisisxsd takes a profisis output file and converts it to BioXsd conform xml. 

.SH OPTIONS 

There are no options. 

.SH AUTHOR 
Jonas Reeb, Robert Wagner, Uwe Altermann

.SH REPORTING BUGS
https://github.com/JonasR/biolab/issues

.SH  COPYRIGHT
Copyright (c) 2013 Free Software Foundation, Inc.  License GPLv3+: GNU GPL  version  3  or
later <http://gnu.org/licenses/gpl.html>. This  is  free  software:  you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
profisis(1)
