.TH PROFISISXSD 1 LOCAL 

.SH NAME 

profisisxsd - print "profisisxsd world" on stdout 

.SH SYNOPSIS 

.B profisisxsd [options] option option [-yy -zz] 

.SH AVAILABILITY 

All UNIX flavors 

.SH DESCRIPTION 

profisisxsd works like the original profisis but writes optional BioXsd output files. 

.SH OPTIONS 

There are no options, but we'll make some up. 

.TP 
-yyl is one option 

.TP 
-zz is another option 

.SH AUTHOR 
Jonas Reeb, Robert Wagner, Uwe Altermann

.SH REPORTING BUGS
currently no known bugs ;-)

.SH  COPYRIGHT
Copyright © 2011 Free Software Foundation, Inc.  License GPLv3+: GNU GPL  version  3  or
later <http://gnu.org/licenses/gpl.html>. This  is  free  software:  you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
The full documentation for profisis is maintained by others.
