//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Alignment of 2..n generic nucleotide or amino-acid sequences. A *multiple sequence alignment* in the sense that all sequences are treated equally
 * 
 * <p>Java class for BiosequenceAlignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiosequenceAlignment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alignedBy" type="{http://bioxsd.org/BioXSD-1.1}MethodResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="alignedSequence" type="{http://bioxsd.org/BioXSD-1.1}AlignedBiosequence" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;element name="note" type="{http://bioxsd.org/BioXSD-1.1}Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiosequenceAlignment", propOrder = {
    "alignedBy",
    "alignedSequence",
    "note"
})
@XmlSeeAlso({
    GeneralAminoacidSequenceAlignment.class,
    GeneralNucleotideSequenceAlignment.class
})
public class BiosequenceAlignment {

    protected List<MethodResult> alignedBy;
    @XmlElement(required = true)
    protected List<AlignedBiosequence> alignedSequence;
    protected String note;

    /**
     * Gets the value of the alignedBy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alignedBy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlignedBy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MethodResult }
     * 
     * 
     */
    public List<MethodResult> getAlignedBy() {
        if (alignedBy == null) {
            alignedBy = new ArrayList<MethodResult>();
        }
        return this.alignedBy;
    }

    /**
     * Gets the value of the alignedSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alignedSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlignedSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AlignedBiosequence }
     * 
     * 
     */
    public List<AlignedBiosequence> getAlignedSequence() {
        if (alignedSequence == null) {
            alignedSequence = new ArrayList<AlignedBiosequence>();
        }
        return this.alignedSequence;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

}
