//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Features of a sequence/biopolymer (or a genome/metagenome).
 * The reference sequence may me included explicitly, referred to remotely, or implicit
 * 
 * <p>Java class for FeatureRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureRecord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referenceSequence">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="sequenceRecord" type="{http://bioxsd.org/BioXSD-1.1}BiosequenceRecord"/>
 *                   &lt;element name="sequenceReference" type="{http://bioxsd.org/BioXSD-1.1}SequenceReference"/>
 *                   &lt;element name="sequenceName" type="{http://bioxsd.org/BioXSD-1.1}Name"/>
 *                   &lt;sequence>
 *                     &lt;element name="species" type="{http://bioxsd.org/BioXSD-1.1}Species"/>
 *                     &lt;element name="genomeBuild" type="{http://bioxsd.org/BioXSD-1.1}EntryReference"/>
 *                     &lt;element name="chromosome" type="{http://bioxsd.org/BioXSD-1.1}ChromosomeName"/>
 *                     &lt;element name="subsequencePosition" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *                     &lt;element name="variantAccession" type="{http://bioxsd.org/BioXSD-1.1}Accession" minOccurs="0"/>
 *                     &lt;element name="variantNote" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="annotation">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="feature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType"/>
 *                     &lt;element name="condensedReferences" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
 *                               &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
 *                               &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
 *                               &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="occurrence" type="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="blockWithOccurrenceReferences">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="database" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://bioxsd.org/BioXSD-1.1}DatabaseReference">
 *                             &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="ontology" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://bioxsd.org/BioXSD-1.1}OntologyReference">
 *                             &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="semanticConcept" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://bioxsd.org/BioXSD-1.1}SemanticConcept">
 *                             &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="method" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://bioxsd.org/BioXSD-1.1}Method">
 *                             &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="scoreType" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{http://bioxsd.org/BioXSD-1.1}ScoreType">
 *                             &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="annotation" maxOccurs="unbounded">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="feature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType"/>
 *                               &lt;element name="condensedReferences" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;choice>
 *                                           &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
 *                                           &lt;element name="methodIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
 *                                         &lt;/choice>
 *                                         &lt;choice>
 *                                           &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
 *                                           &lt;element name="ontologyIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
 *                                         &lt;/choice>
 *                                         &lt;choice>
 *                                           &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
 *                                           &lt;element name="databaseIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
 *                                         &lt;/choice>
 *                                         &lt;choice>
 *                                           &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
 *                                           &lt;element name="scoreTypeIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
 *                                         &lt;/choice>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="occurrence" maxOccurs="unbounded" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData">
 *                                       &lt;sequence>
 *                                         &lt;element name="association" maxOccurs="unbounded" minOccurs="0">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *                                                   &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
 *                                                   &lt;element name="relationConceptIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" maxOccurs="unbounded" minOccurs="0"/>
 *                                                   &lt;element name="associatedFeatureOccurrence" maxOccurs="unbounded">
 *                                                     &lt;complexType>
 *                                                       &lt;complexContent>
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                           &lt;sequence>
 *                                                             &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
 *                                                           &lt;/sequence>
 *                                                           &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                                                         &lt;/restriction>
 *                                                       &lt;/complexContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                       &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *                                     &lt;/extension>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureRecord", propOrder = {
    "referenceSequence",
    "annotationOrBlockWithOccurrenceReferences"
})
public class FeatureRecord {

    @XmlElement(required = true)
    protected FeatureRecord.ReferenceSequence referenceSequence;
    @XmlElements({
        @XmlElement(name = "annotation", type = FeatureRecord.Annotation.class),
        @XmlElement(name = "blockWithOccurrenceReferences", type = FeatureRecord.BlockWithOccurrenceReferences.class)
    })
    protected List<Object> annotationOrBlockWithOccurrenceReferences;

    /**
     * Gets the value of the referenceSequence property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureRecord.ReferenceSequence }
     *     
     */
    public FeatureRecord.ReferenceSequence getReferenceSequence() {
        return referenceSequence;
    }

    /**
     * Sets the value of the referenceSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureRecord.ReferenceSequence }
     *     
     */
    public void setReferenceSequence(FeatureRecord.ReferenceSequence value) {
        this.referenceSequence = value;
    }

    /**
     * Gets the value of the annotationOrBlockWithOccurrenceReferences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationOrBlockWithOccurrenceReferences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationOrBlockWithOccurrenceReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureRecord.Annotation }
     * {@link FeatureRecord.BlockWithOccurrenceReferences }
     * 
     * 
     */
    public List<Object> getAnnotationOrBlockWithOccurrenceReferences() {
        if (annotationOrBlockWithOccurrenceReferences == null) {
            annotationOrBlockWithOccurrenceReferences = new ArrayList<Object>();
        }
        return this.annotationOrBlockWithOccurrenceReferences;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="feature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType"/>
     *         &lt;element name="condensedReferences" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
     *                   &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
     *                   &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
     *                   &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="occurrence" type="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "feature",
        "condensedReferences",
        "occurrence"
    })
    public static class Annotation {

        @XmlElement(required = true)
        protected FeatureType feature;
        protected FeatureRecord.Annotation.CondensedReferences condensedReferences;
        protected List<FeatureOccurrenceData> occurrence;

        /**
         * Gets the value of the feature property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureType }
         *     
         */
        public FeatureType getFeature() {
            return feature;
        }

        /**
         * Sets the value of the feature property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureType }
         *     
         */
        public void setFeature(FeatureType value) {
            this.feature = value;
        }

        /**
         * Gets the value of the condensedReferences property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureRecord.Annotation.CondensedReferences }
         *     
         */
        public FeatureRecord.Annotation.CondensedReferences getCondensedReferences() {
            return condensedReferences;
        }

        /**
         * Sets the value of the condensedReferences property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureRecord.Annotation.CondensedReferences }
         *     
         */
        public void setCondensedReferences(FeatureRecord.Annotation.CondensedReferences value) {
            this.condensedReferences = value;
        }

        /**
         * Gets the value of the occurrence property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the occurrence property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOccurrence().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureOccurrenceData }
         * 
         * 
         */
        public List<FeatureOccurrenceData> getOccurrence() {
            if (occurrence == null) {
                occurrence = new ArrayList<FeatureOccurrenceData>();
            }
            return this.occurrence;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
         *         &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
         *         &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
         *         &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "method",
            "ontology",
            "database",
            "scoreType"
        })
        public static class CondensedReferences {

            protected profisisout.Method method;
            protected OntologyReference ontology;
            protected DatabaseReference database;
            protected profisisout.ScoreType scoreType;

            /**
             * Gets the value of the method property.
             * 
             * @return
             *     possible object is
             *     {@link profisisout.Method }
             *     
             */
            public profisisout.Method getMethod() {
                return method;
            }

            /**
             * Sets the value of the method property.
             * 
             * @param value
             *     allowed object is
             *     {@link profisisout.Method }
             *     
             */
            public void setMethod(profisisout.Method value) {
                this.method = value;
            }

            /**
             * Gets the value of the ontology property.
             * 
             * @return
             *     possible object is
             *     {@link OntologyReference }
             *     
             */
            public OntologyReference getOntology() {
                return ontology;
            }

            /**
             * Sets the value of the ontology property.
             * 
             * @param value
             *     allowed object is
             *     {@link OntologyReference }
             *     
             */
            public void setOntology(OntologyReference value) {
                this.ontology = value;
            }

            /**
             * Gets the value of the database property.
             * 
             * @return
             *     possible object is
             *     {@link DatabaseReference }
             *     
             */
            public DatabaseReference getDatabase() {
                return database;
            }

            /**
             * Sets the value of the database property.
             * 
             * @param value
             *     allowed object is
             *     {@link DatabaseReference }
             *     
             */
            public void setDatabase(DatabaseReference value) {
                this.database = value;
            }

            /**
             * Gets the value of the scoreType property.
             * 
             * @return
             *     possible object is
             *     {@link profisisout.ScoreType }
             *     
             */
            public profisisout.ScoreType getScoreType() {
                return scoreType;
            }

            /**
             * Sets the value of the scoreType property.
             * 
             * @param value
             *     allowed object is
             *     {@link profisisout.ScoreType }
             *     
             */
            public void setScoreType(profisisout.ScoreType value) {
                this.scoreType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="database" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}DatabaseReference">
     *                 &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ontology" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}OntologyReference">
     *                 &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="semanticConcept" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}SemanticConcept">
     *                 &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="method" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}Method">
     *                 &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="scoreType" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}ScoreType">
     *                 &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="annotation" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="feature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType"/>
     *                   &lt;element name="condensedReferences" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;choice>
     *                               &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
     *                               &lt;element name="methodIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
     *                             &lt;/choice>
     *                             &lt;choice>
     *                               &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
     *                               &lt;element name="ontologyIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
     *                             &lt;/choice>
     *                             &lt;choice>
     *                               &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
     *                               &lt;element name="databaseIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
     *                             &lt;/choice>
     *                             &lt;choice>
     *                               &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
     *                               &lt;element name="scoreTypeIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
     *                             &lt;/choice>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="occurrence" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData">
     *                           &lt;sequence>
     *                             &lt;element name="association" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
     *                                       &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
     *                                       &lt;element name="relationConceptIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" maxOccurs="unbounded" minOccurs="0"/>
     *                                       &lt;element name="associatedFeatureOccurrence" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                               &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "database",
        "ontology",
        "semanticConcept",
        "method",
        "scoreType",
        "annotation"
    })
    public static class BlockWithOccurrenceReferences {

        protected List<FeatureRecord.BlockWithOccurrenceReferences.Database> database;
        protected List<FeatureRecord.BlockWithOccurrenceReferences.Ontology> ontology;
        protected List<FeatureRecord.BlockWithOccurrenceReferences.SemanticConcept> semanticConcept;
        protected List<FeatureRecord.BlockWithOccurrenceReferences.Method> method;
        protected List<FeatureRecord.BlockWithOccurrenceReferences.ScoreType> scoreType;
        @XmlElement(required = true)
        protected List<FeatureRecord.BlockWithOccurrenceReferences.Annotation> annotation;

        /**
         * Gets the value of the database property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the database property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatabase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.Database }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.Database> getDatabase() {
            if (database == null) {
                database = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Database>();
            }
            return this.database;
        }

        /**
         * Gets the value of the ontology property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ontology property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOntology().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.Ontology }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.Ontology> getOntology() {
            if (ontology == null) {
                ontology = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Ontology>();
            }
            return this.ontology;
        }

        /**
         * Gets the value of the semanticConcept property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the semanticConcept property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSemanticConcept().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.SemanticConcept }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.SemanticConcept> getSemanticConcept() {
            if (semanticConcept == null) {
                semanticConcept = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.SemanticConcept>();
            }
            return this.semanticConcept;
        }

        /**
         * Gets the value of the method property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the method property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMethod().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.Method }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.Method> getMethod() {
            if (method == null) {
                method = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Method>();
            }
            return this.method;
        }

        /**
         * Gets the value of the scoreType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scoreType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScoreType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.ScoreType }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.ScoreType> getScoreType() {
            if (scoreType == null) {
                scoreType = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.ScoreType>();
            }
            return this.scoreType;
        }

        /**
         * Gets the value of the annotation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the annotation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnnotation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation }
         * 
         * 
         */
        public List<FeatureRecord.BlockWithOccurrenceReferences.Annotation> getAnnotation() {
            if (annotation == null) {
                annotation = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Annotation>();
            }
            return this.annotation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="feature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType"/>
         *         &lt;element name="condensedReferences" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;choice>
         *                     &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
         *                     &lt;element name="methodIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
         *                   &lt;/choice>
         *                   &lt;choice>
         *                     &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
         *                     &lt;element name="ontologyIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
         *                   &lt;/choice>
         *                   &lt;choice>
         *                     &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
         *                     &lt;element name="databaseIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
         *                   &lt;/choice>
         *                   &lt;choice>
         *                     &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
         *                     &lt;element name="scoreTypeIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
         *                   &lt;/choice>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="occurrence" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData">
         *                 &lt;sequence>
         *                   &lt;element name="association" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
         *                             &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
         *                             &lt;element name="relationConceptIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" maxOccurs="unbounded" minOccurs="0"/>
         *                             &lt;element name="associatedFeatureOccurrence" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                     &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "feature",
            "condensedReferences",
            "occurrence"
        })
        public static class Annotation {

            @XmlElement(required = true)
            protected FeatureType feature;
            protected FeatureRecord.BlockWithOccurrenceReferences.Annotation.CondensedReferences condensedReferences;
            protected List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence> occurrence;

            /**
             * Gets the value of the feature property.
             * 
             * @return
             *     possible object is
             *     {@link FeatureType }
             *     
             */
            public FeatureType getFeature() {
                return feature;
            }

            /**
             * Sets the value of the feature property.
             * 
             * @param value
             *     allowed object is
             *     {@link FeatureType }
             *     
             */
            public void setFeature(FeatureType value) {
                this.feature = value;
            }

            /**
             * Gets the value of the condensedReferences property.
             * 
             * @return
             *     possible object is
             *     {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation.CondensedReferences }
             *     
             */
            public FeatureRecord.BlockWithOccurrenceReferences.Annotation.CondensedReferences getCondensedReferences() {
                return condensedReferences;
            }

            /**
             * Sets the value of the condensedReferences property.
             * 
             * @param value
             *     allowed object is
             *     {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation.CondensedReferences }
             *     
             */
            public void setCondensedReferences(FeatureRecord.BlockWithOccurrenceReferences.Annotation.CondensedReferences value) {
                this.condensedReferences = value;
            }

            /**
             * Gets the value of the occurrence property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the occurrence property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOccurrence().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence }
             * 
             * 
             */
            public List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence> getOccurrence() {
                if (occurrence == null) {
                    occurrence = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence>();
                }
                return this.occurrence;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;choice>
             *           &lt;element name="method" type="{http://bioxsd.org/BioXSD-1.1}Method" minOccurs="0"/>
             *           &lt;element name="methodIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
             *         &lt;/choice>
             *         &lt;choice>
             *           &lt;element name="ontology" type="{http://bioxsd.org/BioXSD-1.1}OntologyReference" minOccurs="0"/>
             *           &lt;element name="ontologyIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
             *         &lt;/choice>
             *         &lt;choice>
             *           &lt;element name="database" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" minOccurs="0"/>
             *           &lt;element name="databaseIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
             *         &lt;/choice>
             *         &lt;choice>
             *           &lt;element name="scoreType" type="{http://bioxsd.org/BioXSD-1.1}ScoreType" minOccurs="0"/>
             *           &lt;element name="scoreTypeIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" minOccurs="0"/>
             *         &lt;/choice>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "method",
                "methodIdRef",
                "ontology",
                "ontologyIdRef",
                "database",
                "databaseIdRef",
                "scoreType",
                "scoreTypeIdRef"
            })
            public static class CondensedReferences {

                protected profisisout.Method method;
                protected String methodIdRef;
                protected OntologyReference ontology;
                protected String ontologyIdRef;
                protected DatabaseReference database;
                protected String databaseIdRef;
                protected profisisout.ScoreType scoreType;
                protected String scoreTypeIdRef;

                /**
                 * Gets the value of the method property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link profisisout.Method }
                 *     
                 */
                public profisisout.Method getMethod() {
                    return method;
                }

                /**
                 * Sets the value of the method property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link profisisout.Method }
                 *     
                 */
                public void setMethod(profisisout.Method value) {
                    this.method = value;
                }

                /**
                 * Gets the value of the methodIdRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMethodIdRef() {
                    return methodIdRef;
                }

                /**
                 * Sets the value of the methodIdRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMethodIdRef(String value) {
                    this.methodIdRef = value;
                }

                /**
                 * Gets the value of the ontology property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OntologyReference }
                 *     
                 */
                public OntologyReference getOntology() {
                    return ontology;
                }

                /**
                 * Sets the value of the ontology property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OntologyReference }
                 *     
                 */
                public void setOntology(OntologyReference value) {
                    this.ontology = value;
                }

                /**
                 * Gets the value of the ontologyIdRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOntologyIdRef() {
                    return ontologyIdRef;
                }

                /**
                 * Sets the value of the ontologyIdRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOntologyIdRef(String value) {
                    this.ontologyIdRef = value;
                }

                /**
                 * Gets the value of the database property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DatabaseReference }
                 *     
                 */
                public DatabaseReference getDatabase() {
                    return database;
                }

                /**
                 * Sets the value of the database property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DatabaseReference }
                 *     
                 */
                public void setDatabase(DatabaseReference value) {
                    this.database = value;
                }

                /**
                 * Gets the value of the databaseIdRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDatabaseIdRef() {
                    return databaseIdRef;
                }

                /**
                 * Sets the value of the databaseIdRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDatabaseIdRef(String value) {
                    this.databaseIdRef = value;
                }

                /**
                 * Gets the value of the scoreType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link profisisout.ScoreType }
                 *     
                 */
                public profisisout.ScoreType getScoreType() {
                    return scoreType;
                }

                /**
                 * Sets the value of the scoreType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link profisisout.ScoreType }
                 *     
                 */
                public void setScoreType(profisisout.ScoreType value) {
                    this.scoreType = value;
                }

                /**
                 * Gets the value of the scoreTypeIdRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getScoreTypeIdRef() {
                    return scoreTypeIdRef;
                }

                /**
                 * Sets the value of the scoreTypeIdRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setScoreTypeIdRef(String value) {
                    this.scoreTypeIdRef = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}FeatureOccurrenceData">
             *       &lt;sequence>
             *         &lt;element name="association" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
             *                   &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
             *                   &lt;element name="relationConceptIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" maxOccurs="unbounded" minOccurs="0"/>
             *                   &lt;element name="associatedFeatureOccurrence" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
             *                           &lt;/sequence>
             *                           &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "association"
            })
            public static class Occurrence
                extends FeatureOccurrenceData
            {

                protected List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association> association;
                @XmlAttribute(name = "localId")
                protected String localId;

                /**
                 * Gets the value of the association property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the association property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAssociation().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association }
                 * 
                 * 
                 */
                public List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association> getAssociation() {
                    if (association == null) {
                        association = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association>();
                    }
                    return this.association;
                }

                /**
                 * Gets the value of the localId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocalId() {
                    return localId;
                }

                /**
                 * Sets the value of the localId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocalId(String value) {
                    this.localId = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
                 *         &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
                 *         &lt;element name="relationConceptIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" maxOccurs="unbounded" minOccurs="0"/>
                 *         &lt;element name="associatedFeatureOccurrence" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *                 &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "relationName",
                    "relationConcept",
                    "relationConceptIdRef",
                    "associatedFeatureOccurrence"
                })
                public static class Association {

                    protected String relationName;
                    protected List<profisisout.SemanticConcept> relationConcept;
                    protected List<String> relationConceptIdRef;
                    @XmlElement(required = true)
                    protected List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association.AssociatedFeatureOccurrence> associatedFeatureOccurrence;

                    /**
                     * Gets the value of the relationName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getRelationName() {
                        return relationName;
                    }

                    /**
                     * Sets the value of the relationName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setRelationName(String value) {
                        this.relationName = value;
                    }

                    /**
                     * Gets the value of the relationConcept property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the relationConcept property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getRelationConcept().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link profisisout.SemanticConcept }
                     * 
                     * 
                     */
                    public List<profisisout.SemanticConcept> getRelationConcept() {
                        if (relationConcept == null) {
                            relationConcept = new ArrayList<profisisout.SemanticConcept>();
                        }
                        return this.relationConcept;
                    }

                    /**
                     * Gets the value of the relationConceptIdRef property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the relationConceptIdRef property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getRelationConceptIdRef().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getRelationConceptIdRef() {
                        if (relationConceptIdRef == null) {
                            relationConceptIdRef = new ArrayList<String>();
                        }
                        return this.relationConceptIdRef;
                    }

                    /**
                     * Gets the value of the associatedFeatureOccurrence property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the associatedFeatureOccurrence property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getAssociatedFeatureOccurrence().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association.AssociatedFeatureOccurrence }
                     * 
                     * 
                     */
                    public List<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association.AssociatedFeatureOccurrence> getAssociatedFeatureOccurrence() {
                        if (associatedFeatureOccurrence == null) {
                            associatedFeatureOccurrence = new ArrayList<FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.Association.AssociatedFeatureOccurrence>();
                        }
                        return this.associatedFeatureOccurrence;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
                     *       &lt;/sequence>
                     *       &lt;attribute name="localIdRef" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "score"
                    })
                    public static class AssociatedFeatureOccurrence {

                        protected List<Score> score;
                        @XmlAttribute(name = "localIdRef", required = true)
                        protected String localIdRef;

                        /**
                         * Gets the value of the score property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the score property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getScore().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Score }
                         * 
                         * 
                         */
                        public List<Score> getScore() {
                            if (score == null) {
                                score = new ArrayList<Score>();
                            }
                            return this.score;
                        }

                        /**
                         * Gets the value of the localIdRef property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getLocalIdRef() {
                            return localIdRef;
                        }

                        /**
                         * Sets the value of the localIdRef property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setLocalIdRef(String value) {
                            this.localIdRef = value;
                        }

                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}DatabaseReference">
         *       &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Database
            extends DatabaseReference
        {

            @XmlAttribute(name = "localId", required = true)
            protected String localId;

            /**
             * Gets the value of the localId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalId() {
                return localId;
            }

            /**
             * Sets the value of the localId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalId(String value) {
                this.localId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}Method">
         *       &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Method
            extends profisisout.Method
        {

            @XmlAttribute(name = "localId", required = true)
            protected String localId;

            /**
             * Gets the value of the localId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalId() {
                return localId;
            }

            /**
             * Sets the value of the localId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalId(String value) {
                this.localId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}OntologyReference">
         *       &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Ontology
            extends OntologyReference
        {

            @XmlAttribute(name = "localId", required = true)
            protected String localId;

            /**
             * Gets the value of the localId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalId() {
                return localId;
            }

            /**
             * Sets the value of the localId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalId(String value) {
                this.localId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}ScoreType">
         *       &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ScoreType
            extends profisisout.ScoreType
        {

            @XmlAttribute(name = "localId", required = true)
            protected String localId;

            /**
             * Gets the value of the localId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalId() {
                return localId;
            }

            /**
             * Sets the value of the localId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalId(String value) {
                this.localId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}SemanticConcept">
         *       &lt;attribute name="localId" use="required" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SemanticConcept
            extends profisisout.SemanticConcept
        {

            @XmlAttribute(name = "localId", required = true)
            protected String localId;

            /**
             * Gets the value of the localId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalId() {
                return localId;
            }

            /**
             * Sets the value of the localId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalId(String value) {
                this.localId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="sequenceRecord" type="{http://bioxsd.org/BioXSD-1.1}BiosequenceRecord"/>
     *         &lt;element name="sequenceReference" type="{http://bioxsd.org/BioXSD-1.1}SequenceReference"/>
     *         &lt;element name="sequenceName" type="{http://bioxsd.org/BioXSD-1.1}Name"/>
     *         &lt;sequence>
     *           &lt;element name="species" type="{http://bioxsd.org/BioXSD-1.1}Species"/>
     *           &lt;element name="genomeBuild" type="{http://bioxsd.org/BioXSD-1.1}EntryReference"/>
     *           &lt;element name="chromosome" type="{http://bioxsd.org/BioXSD-1.1}ChromosomeName"/>
     *           &lt;element name="subsequencePosition" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
     *           &lt;element name="variantAccession" type="{http://bioxsd.org/BioXSD-1.1}Accession" minOccurs="0"/>
     *           &lt;element name="variantNote" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sequenceRecord",
        "sequenceReference",
        "sequenceName",
        "species",
        "genomeBuild",
        "chromosome",
        "subsequencePosition",
        "variantAccession",
        "variantNote"
    })
    public static class ReferenceSequence {

        protected BiosequenceRecord sequenceRecord;
        protected SequenceReference sequenceReference;
        protected String sequenceName;
        protected Species species;
        protected EntryReference genomeBuild;
        protected String chromosome;
        protected SequencePosition subsequencePosition;
        protected String variantAccession;
        protected String variantNote;

        /**
         * Gets the value of the sequenceRecord property.
         * 
         * @return
         *     possible object is
         *     {@link BiosequenceRecord }
         *     
         */
        public BiosequenceRecord getSequenceRecord() {
            return sequenceRecord;
        }

        /**
         * Sets the value of the sequenceRecord property.
         * 
         * @param value
         *     allowed object is
         *     {@link BiosequenceRecord }
         *     
         */
        public void setSequenceRecord(BiosequenceRecord value) {
            this.sequenceRecord = value;
        }

        /**
         * Gets the value of the sequenceReference property.
         * 
         * @return
         *     possible object is
         *     {@link SequenceReference }
         *     
         */
        public SequenceReference getSequenceReference() {
            return sequenceReference;
        }

        /**
         * Sets the value of the sequenceReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link SequenceReference }
         *     
         */
        public void setSequenceReference(SequenceReference value) {
            this.sequenceReference = value;
        }

        /**
         * Gets the value of the sequenceName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSequenceName() {
            return sequenceName;
        }

        /**
         * Sets the value of the sequenceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSequenceName(String value) {
            this.sequenceName = value;
        }

        /**
         * Gets the value of the species property.
         * 
         * @return
         *     possible object is
         *     {@link Species }
         *     
         */
        public Species getSpecies() {
            return species;
        }

        /**
         * Sets the value of the species property.
         * 
         * @param value
         *     allowed object is
         *     {@link Species }
         *     
         */
        public void setSpecies(Species value) {
            this.species = value;
        }

        /**
         * Gets the value of the genomeBuild property.
         * 
         * @return
         *     possible object is
         *     {@link EntryReference }
         *     
         */
        public EntryReference getGenomeBuild() {
            return genomeBuild;
        }

        /**
         * Sets the value of the genomeBuild property.
         * 
         * @param value
         *     allowed object is
         *     {@link EntryReference }
         *     
         */
        public void setGenomeBuild(EntryReference value) {
            this.genomeBuild = value;
        }

        /**
         * Gets the value of the chromosome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChromosome() {
            return chromosome;
        }

        /**
         * Sets the value of the chromosome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChromosome(String value) {
            this.chromosome = value;
        }

        /**
         * Gets the value of the subsequencePosition property.
         * 
         * @return
         *     possible object is
         *     {@link SequencePosition }
         *     
         */
        public SequencePosition getSubsequencePosition() {
            return subsequencePosition;
        }

        /**
         * Sets the value of the subsequencePosition property.
         * 
         * @param value
         *     allowed object is
         *     {@link SequencePosition }
         *     
         */
        public void setSubsequencePosition(SequencePosition value) {
            this.subsequencePosition = value;
        }

        /**
         * Gets the value of the variantAccession property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariantAccession() {
            return variantAccession;
        }

        /**
         * Sets the value of the variantAccession property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariantAccession(String value) {
            this.variantAccession = value;
        }

        /**
         * Gets the value of the variantNote property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariantNote() {
            return variantNote;
        }

        /**
         * Sets the value of the variantNote property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariantNote(String value) {
            this.variantNote = value;
        }

    }

}
