//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Occurrence of a feature in a reference sequence. Positioned or non-positioned (non-positioned means applied to the whole sequence)
 * 
 * <p>Java class for FeatureOccurrenceData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureOccurrenceData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="appliesToWholeSequence" type="{http://bioxsd.org/BioXSD-1.1}Flag"/>
 *           &lt;element name="position" type="{http://bioxsd.org/BioXSD-1.1}GeneralSequencePosition"/>
 *         &lt;/choice>
 *         &lt;element name="occurrenceEntryReference" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="occurrenceName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *         &lt;element name="occurrenceNote" type="{http://bioxsd.org/BioXSD-1.1}Text" minOccurs="0"/>
 *         &lt;element name="featureTypeDetails" type="{http://bioxsd.org/BioXSD-1.1}FeatureTypeDetails" minOccurs="0"/>
 *         &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="evidence" type="{http://bioxsd.org/BioXSD-1.1}Evidence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="frame" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}AnyInteger">
 *               &lt;minInclusive value="-3"/>
 *               &lt;maxInclusive value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="phase" type="{http://bioxsd.org/BioXSD-1.1}Phase" minOccurs="0"/>
 *         &lt;element name="variation" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="canonicalVariant" type="{http://bioxsd.org/BioXSD-1.1}Biosequence" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="variant" type="{http://bioxsd.org/BioXSD-1.1}Biosequence" maxOccurs="unbounded"/>
 *                     &lt;element name="missing" type="{http://bioxsd.org/BioXSD-1.1}Flag"/>
 *                   &lt;/choice>
 *                   &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="position" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="alignment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="alignmentOfReference" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="gap" type="{http://bioxsd.org/BioXSD-1.1}Gap" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="insert" type="{http://bioxsd.org/BioXSD-1.1}Insert" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="frameshift" type="{http://bioxsd.org/BioXSD-1.1}Frameshift" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="sequenceScore" type="{http://bioxsd.org/BioXSD-1.1}Result" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="alignedSequence" type="{http://bioxsd.org/BioXSD-1.1}AlignedBiosequence"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureOccurrenceData", propOrder = {
    "appliesToWholeSequence",
    "position",
    "occurrenceEntryReference",
    "occurrenceName",
    "occurrenceNote",
    "featureTypeDetails",
    "score",
    "evidence",
    "frame",
    "phase",
    "variation",
    "alignment"
})
@XmlSeeAlso({
    profisisout.FeatureRecord.BlockWithOccurrenceReferences.Annotation.Occurrence.class
})
public class FeatureOccurrenceData {

    protected Flag appliesToWholeSequence;
    protected GeneralSequencePosition position;
    protected List<EntryReference> occurrenceEntryReference;
    protected String occurrenceName;
    protected String occurrenceNote;
    protected FeatureTypeDetails featureTypeDetails;
    protected List<Score> score;
    protected List<Evidence> evidence;
    protected Integer frame;
    protected Integer phase;
    protected List<FeatureOccurrenceData.Variation> variation;
    protected FeatureOccurrenceData.Alignment alignment;

    /**
     * Gets the value of the appliesToWholeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link Flag }
     *     
     */
    public Flag getAppliesToWholeSequence() {
        return appliesToWholeSequence;
    }

    /**
     * Sets the value of the appliesToWholeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flag }
     *     
     */
    public void setAppliesToWholeSequence(Flag value) {
        this.appliesToWholeSequence = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralSequencePosition }
     *     
     */
    public GeneralSequencePosition getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralSequencePosition }
     *     
     */
    public void setPosition(GeneralSequencePosition value) {
        this.position = value;
    }

    /**
     * Gets the value of the occurrenceEntryReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the occurrenceEntryReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOccurrenceEntryReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntryReference }
     * 
     * 
     */
    public List<EntryReference> getOccurrenceEntryReference() {
        if (occurrenceEntryReference == null) {
            occurrenceEntryReference = new ArrayList<EntryReference>();
        }
        return this.occurrenceEntryReference;
    }

    /**
     * Gets the value of the occurrenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccurrenceName() {
        return occurrenceName;
    }

    /**
     * Sets the value of the occurrenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccurrenceName(String value) {
        this.occurrenceName = value;
    }

    /**
     * Gets the value of the occurrenceNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccurrenceNote() {
        return occurrenceNote;
    }

    /**
     * Sets the value of the occurrenceNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccurrenceNote(String value) {
        this.occurrenceNote = value;
    }

    /**
     * Gets the value of the featureTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureTypeDetails }
     *     
     */
    public FeatureTypeDetails getFeatureTypeDetails() {
        return featureTypeDetails;
    }

    /**
     * Sets the value of the featureTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureTypeDetails }
     *     
     */
    public void setFeatureTypeDetails(FeatureTypeDetails value) {
        this.featureTypeDetails = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the score property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Score }
     * 
     * 
     */
    public List<Score> getScore() {
        if (score == null) {
            score = new ArrayList<Score>();
        }
        return this.score;
    }

    /**
     * Gets the value of the evidence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Evidence }
     * 
     * 
     */
    public List<Evidence> getEvidence() {
        if (evidence == null) {
            evidence = new ArrayList<Evidence>();
        }
        return this.evidence;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrame(Integer value) {
        this.frame = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPhase(Integer value) {
        this.phase = value;
    }

    /**
     * Gets the value of the variation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureOccurrenceData.Variation }
     * 
     * 
     */
    public List<FeatureOccurrenceData.Variation> getVariation() {
        if (variation == null) {
            variation = new ArrayList<FeatureOccurrenceData.Variation>();
        }
        return this.variation;
    }

    /**
     * Gets the value of the alignment property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureOccurrenceData.Alignment }
     *     
     */
    public FeatureOccurrenceData.Alignment getAlignment() {
        return alignment;
    }

    /**
     * Sets the value of the alignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureOccurrenceData.Alignment }
     *     
     */
    public void setAlignment(FeatureOccurrenceData.Alignment value) {
        this.alignment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="alignmentOfReference" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="gap" type="{http://bioxsd.org/BioXSD-1.1}Gap" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="insert" type="{http://bioxsd.org/BioXSD-1.1}Insert" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="frameshift" type="{http://bioxsd.org/BioXSD-1.1}Frameshift" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="sequenceScore" type="{http://bioxsd.org/BioXSD-1.1}Result" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="alignedSequence" type="{http://bioxsd.org/BioXSD-1.1}AlignedBiosequence"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alignmentOfReference",
        "alignedSequence"
    })
    public static class Alignment {

        protected FeatureOccurrenceData.Alignment.AlignmentOfReference alignmentOfReference;
        @XmlElement(required = true)
        protected AlignedBiosequence alignedSequence;

        /**
         * Gets the value of the alignmentOfReference property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureOccurrenceData.Alignment.AlignmentOfReference }
         *     
         */
        public FeatureOccurrenceData.Alignment.AlignmentOfReference getAlignmentOfReference() {
            return alignmentOfReference;
        }

        /**
         * Sets the value of the alignmentOfReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureOccurrenceData.Alignment.AlignmentOfReference }
         *     
         */
        public void setAlignmentOfReference(FeatureOccurrenceData.Alignment.AlignmentOfReference value) {
            this.alignmentOfReference = value;
        }

        /**
         * Gets the value of the alignedSequence property.
         * 
         * @return
         *     possible object is
         *     {@link AlignedBiosequence }
         *     
         */
        public AlignedBiosequence getAlignedSequence() {
            return alignedSequence;
        }

        /**
         * Sets the value of the alignedSequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlignedBiosequence }
         *     
         */
        public void setAlignedSequence(AlignedBiosequence value) {
            this.alignedSequence = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="gap" type="{http://bioxsd.org/BioXSD-1.1}Gap" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="insert" type="{http://bioxsd.org/BioXSD-1.1}Insert" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="frameshift" type="{http://bioxsd.org/BioXSD-1.1}Frameshift" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="sequenceScore" type="{http://bioxsd.org/BioXSD-1.1}Result" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "gap",
            "insert",
            "frameshift",
            "sequenceScore"
        })
        public static class AlignmentOfReference {

            protected List<Gap> gap;
            protected List<Insert> insert;
            protected List<Frameshift> frameshift;
            protected List<Result> sequenceScore;

            /**
             * Gets the value of the gap property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the gap property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGap().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Gap }
             * 
             * 
             */
            public List<Gap> getGap() {
                if (gap == null) {
                    gap = new ArrayList<Gap>();
                }
                return this.gap;
            }

            /**
             * Gets the value of the insert property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the insert property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInsert().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Insert }
             * 
             * 
             */
            public List<Insert> getInsert() {
                if (insert == null) {
                    insert = new ArrayList<Insert>();
                }
                return this.insert;
            }

            /**
             * Gets the value of the frameshift property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the frameshift property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFrameshift().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Frameshift }
             * 
             * 
             */
            public List<Frameshift> getFrameshift() {
                if (frameshift == null) {
                    frameshift = new ArrayList<Frameshift>();
                }
                return this.frameshift;
            }

            /**
             * Gets the value of the sequenceScore property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sequenceScore property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSequenceScore().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Result }
             * 
             * 
             */
            public List<Result> getSequenceScore() {
                if (sequenceScore == null) {
                    sequenceScore = new ArrayList<Result>();
                }
                return this.sequenceScore;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="canonicalVariant" type="{http://bioxsd.org/BioXSD-1.1}Biosequence" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="variant" type="{http://bioxsd.org/BioXSD-1.1}Biosequence" maxOccurs="unbounded"/>
     *           &lt;element name="missing" type="{http://bioxsd.org/BioXSD-1.1}Flag"/>
     *         &lt;/choice>
     *         &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="position" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "canonicalVariant",
        "variant",
        "missing",
        "score",
        "position"
    })
    public static class Variation {

        protected String canonicalVariant;
        protected List<String> variant;
        protected Flag missing;
        protected List<Score> score;
        protected SequencePosition position;

        /**
         * Gets the value of the canonicalVariant property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCanonicalVariant() {
            return canonicalVariant;
        }

        /**
         * Sets the value of the canonicalVariant property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCanonicalVariant(String value) {
            this.canonicalVariant = value;
        }

        /**
         * Gets the value of the variant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the variant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVariant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVariant() {
            if (variant == null) {
                variant = new ArrayList<String>();
            }
            return this.variant;
        }

        /**
         * Gets the value of the missing property.
         * 
         * @return
         *     possible object is
         *     {@link Flag }
         *     
         */
        public Flag getMissing() {
            return missing;
        }

        /**
         * Sets the value of the missing property.
         * 
         * @param value
         *     allowed object is
         *     {@link Flag }
         *     
         */
        public void setMissing(Flag value) {
            this.missing = value;
        }

        /**
         * Gets the value of the score property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the score property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Score }
         * 
         * 
         */
        public List<Score> getScore() {
            if (score == null) {
                score = new ArrayList<Score>();
            }
            return this.score;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link SequencePosition }
         *     
         */
        public SequencePosition getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link SequencePosition }
         *     
         */
        public void setPosition(SequencePosition value) {
            this.position = value;
        }

    }

}
