//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specific properties of a feature
 * 
 * <p>Java class for FeatureTypeDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureTypeDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="specificFeatureName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *         &lt;element name="specificFeatureConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specificFeatureAlias" type="{http://bioxsd.org/BioXSD-1.1}Name" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="databaseEntry" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="note" type="{http://bioxsd.org/BioXSD-1.1}Text" minOccurs="0"/>
 *         &lt;element name="association" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *                   &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;choice>
 *                     &lt;element name="associatedConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded"/>
 *                     &lt;element name="associatedDatabaseEntry" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" maxOccurs="unbounded"/>
 *                     &lt;element name="associatedDatabase" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" maxOccurs="unbounded"/>
 *                     &lt;element name="associatedFeature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType" maxOccurs="unbounded"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureTypeDetails", propOrder = {
    "specificFeatureName",
    "specificFeatureConcept",
    "specificFeatureAlias",
    "databaseEntry",
    "note",
    "association"
})
public class FeatureTypeDetails {

    protected String specificFeatureName;
    protected List<SemanticConcept> specificFeatureConcept;
    protected List<String> specificFeatureAlias;
    protected List<EntryReference> databaseEntry;
    protected String note;
    protected List<FeatureTypeDetails.Association> association;

    /**
     * Gets the value of the specificFeatureName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificFeatureName() {
        return specificFeatureName;
    }

    /**
     * Sets the value of the specificFeatureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificFeatureName(String value) {
        this.specificFeatureName = value;
    }

    /**
     * Gets the value of the specificFeatureConcept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificFeatureConcept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificFeatureConcept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SemanticConcept }
     * 
     * 
     */
    public List<SemanticConcept> getSpecificFeatureConcept() {
        if (specificFeatureConcept == null) {
            specificFeatureConcept = new ArrayList<SemanticConcept>();
        }
        return this.specificFeatureConcept;
    }

    /**
     * Gets the value of the specificFeatureAlias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificFeatureAlias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificFeatureAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecificFeatureAlias() {
        if (specificFeatureAlias == null) {
            specificFeatureAlias = new ArrayList<String>();
        }
        return this.specificFeatureAlias;
    }

    /**
     * Gets the value of the databaseEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the databaseEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabaseEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntryReference }
     * 
     * 
     */
    public List<EntryReference> getDatabaseEntry() {
        if (databaseEntry == null) {
            databaseEntry = new ArrayList<EntryReference>();
        }
        return this.databaseEntry;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the association property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the association property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureTypeDetails.Association }
     * 
     * 
     */
    public List<FeatureTypeDetails.Association> getAssociation() {
        if (association == null) {
            association = new ArrayList<FeatureTypeDetails.Association>();
        }
        return this.association;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="relationName" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
     *         &lt;element name="relationConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;choice>
     *           &lt;element name="associatedConcept" type="{http://bioxsd.org/BioXSD-1.1}SemanticConcept" maxOccurs="unbounded"/>
     *           &lt;element name="associatedDatabaseEntry" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" maxOccurs="unbounded"/>
     *           &lt;element name="associatedDatabase" type="{http://bioxsd.org/BioXSD-1.1}DatabaseReference" maxOccurs="unbounded"/>
     *           &lt;element name="associatedFeature" type="{http://bioxsd.org/BioXSD-1.1}FeatureType" maxOccurs="unbounded"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relationName",
        "relationConcept",
        "associatedConcept",
        "associatedDatabaseEntry",
        "associatedDatabase",
        "associatedFeature"
    })
    public static class Association {

        protected String relationName;
        protected List<SemanticConcept> relationConcept;
        protected List<SemanticConcept> associatedConcept;
        protected List<EntryReference> associatedDatabaseEntry;
        protected List<DatabaseReference> associatedDatabase;
        protected List<FeatureType> associatedFeature;

        /**
         * Gets the value of the relationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRelationName() {
            return relationName;
        }

        /**
         * Sets the value of the relationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRelationName(String value) {
            this.relationName = value;
        }

        /**
         * Gets the value of the relationConcept property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relationConcept property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelationConcept().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SemanticConcept }
         * 
         * 
         */
        public List<SemanticConcept> getRelationConcept() {
            if (relationConcept == null) {
                relationConcept = new ArrayList<SemanticConcept>();
            }
            return this.relationConcept;
        }

        /**
         * Gets the value of the associatedConcept property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the associatedConcept property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssociatedConcept().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SemanticConcept }
         * 
         * 
         */
        public List<SemanticConcept> getAssociatedConcept() {
            if (associatedConcept == null) {
                associatedConcept = new ArrayList<SemanticConcept>();
            }
            return this.associatedConcept;
        }

        /**
         * Gets the value of the associatedDatabaseEntry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the associatedDatabaseEntry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssociatedDatabaseEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EntryReference }
         * 
         * 
         */
        public List<EntryReference> getAssociatedDatabaseEntry() {
            if (associatedDatabaseEntry == null) {
                associatedDatabaseEntry = new ArrayList<EntryReference>();
            }
            return this.associatedDatabaseEntry;
        }

        /**
         * Gets the value of the associatedDatabase property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the associatedDatabase property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssociatedDatabase().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseReference }
         * 
         * 
         */
        public List<DatabaseReference> getAssociatedDatabase() {
            if (associatedDatabase == null) {
                associatedDatabase = new ArrayList<DatabaseReference>();
            }
            return this.associatedDatabase;
        }

        /**
         * Gets the value of the associatedFeature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the associatedFeature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssociatedFeature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FeatureType }
         * 
         * 
         */
        public List<FeatureType> getAssociatedFeature() {
            if (associatedFeature == null) {
                associatedFeature = new ArrayList<FeatureType>();
            }
            return this.associatedFeature;
        }

    }

}
