//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Frame-shift in an aligned amino-acid sequence
 * 
 * <p>Java class for Frameshift complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Frameshift">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pos" use="required" type="{http://bioxsd.org/BioXSD-1.1}InsertionInteger" />
 *       &lt;attribute name="bases" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}NonzeroInteger">
 *             &lt;minInclusive value="-2"/>
 *             &lt;maxInclusive value="2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Frameshift")
public class Frameshift {

    @XmlAttribute(name = "pos", required = true)
    protected long pos;
    @XmlAttribute(name = "bases", required = true)
    protected int bases;

    /**
     * Gets the value of the pos property.
     * 
     */
    public long getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     */
    public void setPos(long value) {
        this.pos = value;
    }

    /**
     * Gets the value of the bases property.
     * 
     */
    public int getBases() {
        return bases;
    }

    /**
     * Sets the value of the bases property.
     * 
     */
    public void setBases(int value) {
        this.bases = value;
    }

}
