//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Position outside of the sequence, possibly uncertain
 * 
 * <p>Java class for GeneralOutsideSequencePosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralOutsideSequencePosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="correspondance" type="{http://bioxsd.org/BioXSD-1.1}OutsidePositionCorrespondance"/>
 *           &lt;choice>
 *             &lt;element name="point" type="{http://bioxsd.org/BioXSD-1.1}GeneralOutsideSequencePoint" maxOccurs="unbounded"/>
 *             &lt;element name="insertion" type="{http://bioxsd.org/BioXSD-1.1}GeneralOutsideSequencePoint"/>
 *             &lt;element name="segment" type="{http://bioxsd.org/BioXSD-1.1}GeneralOutsideSequenceSegment" maxOccurs="unbounded"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;element name="explicitSequenceReference" type="{http://bioxsd.org/BioXSD-1.1}SequenceReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralOutsideSequencePosition", propOrder = {
    "correspondance",
    "point",
    "insertion",
    "segment",
    "explicitSequenceReference"
})
@XmlSeeAlso({
    OutsideSequencePosition.class
})
public class GeneralOutsideSequencePosition {

    protected OutsidePositionCorrespondance correspondance;
    protected List<GeneralOutsideSequencePoint> point;
    protected GeneralOutsideSequencePoint insertion;
    protected List<GeneralOutsideSequenceSegment> segment;
    protected SequenceReference explicitSequenceReference;

    /**
     * Gets the value of the correspondance property.
     * 
     * @return
     *     possible object is
     *     {@link OutsidePositionCorrespondance }
     *     
     */
    public OutsidePositionCorrespondance getCorrespondance() {
        return correspondance;
    }

    /**
     * Sets the value of the correspondance property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutsidePositionCorrespondance }
     *     
     */
    public void setCorrespondance(OutsidePositionCorrespondance value) {
        this.correspondance = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneralOutsideSequencePoint }
     * 
     * 
     */
    public List<GeneralOutsideSequencePoint> getPoint() {
        if (point == null) {
            point = new ArrayList<GeneralOutsideSequencePoint>();
        }
        return this.point;
    }

    /**
     * Gets the value of the insertion property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralOutsideSequencePoint }
     *     
     */
    public GeneralOutsideSequencePoint getInsertion() {
        return insertion;
    }

    /**
     * Sets the value of the insertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralOutsideSequencePoint }
     *     
     */
    public void setInsertion(GeneralOutsideSequencePoint value) {
        this.insertion = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneralOutsideSequenceSegment }
     * 
     * 
     */
    public List<GeneralOutsideSequenceSegment> getSegment() {
        if (segment == null) {
            segment = new ArrayList<GeneralOutsideSequenceSegment>();
        }
        return this.segment;
    }

    /**
     * Gets the value of the explicitSequenceReference property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceReference }
     *     
     */
    public SequenceReference getExplicitSequenceReference() {
        return explicitSequenceReference;
    }

    /**
     * Sets the value of the explicitSequenceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceReference }
     *     
     */
    public void setExplicitSequenceReference(SequenceReference value) {
        this.explicitSequenceReference = value;
    }

}
