//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Particular genetic code (codon encoding)
 * 
 * <p>Java class for GeneticCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneticCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference" type="{http://bioxsd.org/BioXSD-1.1}EntryReference" minOccurs="0"/>
 *         &lt;element name="codon" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="code" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}GeneralNucleotideSequence">
 *                       &lt;length value="3"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="aminoacid">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}GeneralAminoacidSequence">
 *                       &lt;length value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="veryRare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="note" type="{http://bioxsd.org/BioXSD-1.1}Text" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneticCode", propOrder = {
    "reference",
    "codon"
})
public class GeneticCode {

    protected EntryReference reference;
    protected List<GeneticCode.Codon> codon;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link EntryReference }
     *     
     */
    public EntryReference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryReference }
     *     
     */
    public void setReference(EntryReference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the codon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeneticCode.Codon }
     * 
     * 
     */
    public List<GeneticCode.Codon> getCodon() {
        if (codon == null) {
            codon = new ArrayList<GeneticCode.Codon>();
        }
        return this.codon;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="code" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}GeneralNucleotideSequence">
     *             &lt;length value="3"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="aminoacid">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}GeneralAminoacidSequence">
     *             &lt;length value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="veryRare" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *       &lt;attribute name="note" type="{http://bioxsd.org/BioXSD-1.1}Text" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Codon {

        @XmlAttribute(name = "code", required = true)
        protected String code;
        @XmlAttribute(name = "start")
        protected Boolean start;
        @XmlAttribute(name = "end")
        protected Boolean end;
        @XmlAttribute(name = "aminoacid")
        protected String aminoacid;
        @XmlAttribute(name = "veryRare")
        protected Boolean veryRare;
        @XmlAttribute(name = "note")
        protected String note;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the start property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isStart() {
            if (start == null) {
                return false;
            } else {
                return start;
            }
        }

        /**
         * Sets the value of the start property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setStart(Boolean value) {
            this.start = value;
        }

        /**
         * Gets the value of the end property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isEnd() {
            if (end == null) {
                return false;
            } else {
                return end;
            }
        }

        /**
         * Sets the value of the end property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setEnd(Boolean value) {
            this.end = value;
        }

        /**
         * Gets the value of the aminoacid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAminoacid() {
            return aminoacid;
        }

        /**
         * Sets the value of the aminoacid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAminoacid(String value) {
            this.aminoacid = value;
        }

        /**
         * Gets the value of the veryRare property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isVeryRare() {
            if (veryRare == null) {
                return false;
            } else {
                return veryRare;
            }
        }

        /**
         * Sets the value of the veryRare property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setVeryRare(Boolean value) {
            this.veryRare = value;
        }

        /**
         * Gets the value of the note property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNote() {
            return note;
        }

        /**
         * Sets the value of the note property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNote(String value) {
            this.note = value;
        }

    }

}
