//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference to an ontology, controlled vocabulary, or a collection of semantic concepts
 * 
 * <p>Java class for OntologyReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OntologyReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ontologyName" type="{http://bioxsd.org/BioXSD-1.1}OntologyName" />
 *       &lt;attribute name="ontologyUri" type="{http://bioxsd.org/BioXSD-1.1}Uri" />
 *       &lt;attribute name="ontologyVersion" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *       &lt;attribute name="localCopyOfOntology" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OntologyReference")
@XmlSeeAlso({
    profisisout.FeatureRecord.BlockWithOccurrenceReferences.Ontology.class,
    SemanticConcept.class
})
public class OntologyReference {

    @XmlAttribute(name = "ontologyName")
    protected String ontologyName;
    @XmlAttribute(name = "ontologyUri")
    protected String ontologyUri;
    @XmlAttribute(name = "ontologyVersion")
    protected String ontologyVersion;
    @XmlAttribute(name = "localCopyOfOntology")
    protected Boolean localCopyOfOntology;

    /**
     * Gets the value of the ontologyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyName() {
        return ontologyName;
    }

    /**
     * Sets the value of the ontologyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyName(String value) {
        this.ontologyName = value;
    }

    /**
     * Gets the value of the ontologyUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyUri() {
        return ontologyUri;
    }

    /**
     * Sets the value of the ontologyUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyUri(String value) {
        this.ontologyUri = value;
    }

    /**
     * Gets the value of the ontologyVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOntologyVersion() {
        return ontologyVersion;
    }

    /**
     * Sets the value of the ontologyVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOntologyVersion(String value) {
        this.ontologyVersion = value;
    }

    /**
     * Gets the value of the localCopyOfOntology property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLocalCopyOfOntology() {
        if (localCopyOfOntology == null) {
            return false;
        } else {
            return localCopyOfOntology;
        }
    }

    /**
     * Sets the value of the localCopyOfOntology property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLocalCopyOfOntology(Boolean value) {
        this.localCopyOfOntology = value;
    }

}
