//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://bioxsd.org/BioXSD-1.1", 
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns={
				
				@XmlNs(prefix="bx", namespaceURI="http://bioxsd.org/BioXSD-1.1"),
				@XmlNs(prefix="fox", namespaceURI="http://i12r-tbl.informatik.tu-muenchen.de/~jonas/profisis/output")
				}
		)

package profisisout;
import javax.xml.bind.annotation.*;
