//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecommendedDatabaseName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecommendedDatabaseName">
 *   &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}Name">
 *     &lt;enumeration value="EMBL"/>
 *     &lt;enumeration value="EMBLCON"/>
 *     &lt;enumeration value="EMBLANN"/>
 *     &lt;enumeration value="EMBLCDS"/>
 *     &lt;enumeration value="EMBLSVA"/>
 *     &lt;enumeration value="Ensembl Gene"/>
 *     &lt;enumeration value="Ensembl Transcript"/>
 *     &lt;enumeration value="UniProt"/>
 *     &lt;enumeration value="UniProt/Swiss-Prot"/>
 *     &lt;enumeration value="UniProt/TrEMBL"/>
 *     &lt;enumeration value="UniSave"/>
 *     &lt;enumeration value="UniRef100"/>
 *     &lt;enumeration value="UniRef90"/>
 *     &lt;enumeration value="UniRef50"/>
 *     &lt;enumeration value="UniParc"/>
 *     &lt;enumeration value="IPI"/>
 *     &lt;enumeration value="RefSeq"/>
 *     &lt;enumeration value="InterPro"/>
 *     &lt;enumeration value="PDB"/>
 *     &lt;enumeration value="HGVbase"/>
 *     &lt;enumeration value="GenomeReviews"/>
 *     &lt;enumeration value="EPO Proteins"/>
 *     &lt;enumeration value="JPO Proteins"/>
 *     &lt;enumeration value="KIPO Proteins"/>
 *     &lt;enumeration value="USPO Proteins"/>
 *     &lt;enumeration value="PubMed"/>
 *     &lt;enumeration value="Medline"/>
 *     &lt;enumeration value="DDBJ/GenBank/EMBL"/>
 *     &lt;enumeration value="PDB"/>
 *     &lt;enumeration value="DAD"/>
 *     &lt;enumeration value="PRF"/>
 *     &lt;enumeration value="Patent"/>
 *     &lt;enumeration value="NCBI Taxonomy"/>
 *     &lt;enumeration value="NCBI Genetic Code"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecommendedDatabaseName")
@XmlEnum
public enum RecommendedDatabaseName {

    EMBL("EMBL"),
    EMBLCON("EMBLCON"),
    EMBLANN("EMBLANN"),
    EMBLCDS("EMBLCDS"),
    EMBLSVA("EMBLSVA"),
    @XmlEnumValue("Ensembl Gene")
    ENSEMBL_GENE("Ensembl Gene"),
    @XmlEnumValue("Ensembl Transcript")
    ENSEMBL_TRANSCRIPT("Ensembl Transcript"),
    @XmlEnumValue("UniProt")
    UNI_PROT("UniProt"),
    @XmlEnumValue("UniProt/Swiss-Prot")
    UNI_PROT_SWISS_PROT("UniProt/Swiss-Prot"),
    @XmlEnumValue("UniProt/TrEMBL")
    UNI_PROT_TR_EMBL("UniProt/TrEMBL"),
    @XmlEnumValue("UniSave")
    UNI_SAVE("UniSave"),
    @XmlEnumValue("UniRef100")
    UNI_REF_100("UniRef100"),
    @XmlEnumValue("UniRef90")
    UNI_REF_90("UniRef90"),
    @XmlEnumValue("UniRef50")
    UNI_REF_50("UniRef50"),
    @XmlEnumValue("UniParc")
    UNI_PARC("UniParc"),
    IPI("IPI"),
    @XmlEnumValue("RefSeq")
    REF_SEQ("RefSeq"),
    @XmlEnumValue("InterPro")
    INTER_PRO("InterPro"),
    PDB("PDB"),
    @XmlEnumValue("HGVbase")
    HG_VBASE("HGVbase"),
    @XmlEnumValue("GenomeReviews")
    GENOME_REVIEWS("GenomeReviews"),
    @XmlEnumValue("EPO Proteins")
    EPO_PROTEINS("EPO Proteins"),
    @XmlEnumValue("JPO Proteins")
    JPO_PROTEINS("JPO Proteins"),
    @XmlEnumValue("KIPO Proteins")
    KIPO_PROTEINS("KIPO Proteins"),
    @XmlEnumValue("USPO Proteins")
    USPO_PROTEINS("USPO Proteins"),
    @XmlEnumValue("PubMed")
    PUB_MED("PubMed"),
    @XmlEnumValue("Medline")
    MEDLINE("Medline"),
    @XmlEnumValue("DDBJ/GenBank/EMBL")
    DDBJ_GEN_BANK_EMBL("DDBJ/GenBank/EMBL"),
    DAD("DAD"),
    PRF("PRF"),
    @XmlEnumValue("Patent")
    PATENT("Patent"),
    @XmlEnumValue("NCBI Taxonomy")
    NCBI_TAXONOMY("NCBI Taxonomy"),
    @XmlEnumValue("NCBI Genetic Code")
    NCBI_GENETIC_CODE("NCBI Genetic Code");
    private final String value;

    RecommendedDatabaseName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecommendedDatabaseName fromValue(String v) {
        for (RecommendedDatabaseName c: RecommendedDatabaseName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
