//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.26 at 10:17:24 PM CEST 
//


package profisisout;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecommendedReliability.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecommendedReliability">
 *   &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}Name">
 *     &lt;enumeration value="Reliable"/>
 *     &lt;enumeration value="Disputable"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecommendedReliability")
@XmlEnum
public enum RecommendedReliability {

    @XmlEnumValue("Reliable")
    RELIABLE("Reliable"),
    @XmlEnumValue("Disputable")
    DISPUTABLE("Disputable");
    private final String value;

    RecommendedReliability(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecommendedReliability fromValue(String v) {
        for (RecommendedReliability c: RecommendedReliability.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
