//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlignedBiosequence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlignedBiosequence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="localAlignmentPosition" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="sequenceRecord" type="{http://bioxsd.org/BioXSD-1.1}BiosequenceRecord"/>
 *           &lt;element name="sequenceReference" type="{http://bioxsd.org/BioXSD-1.1}SequenceReference"/>
 *           &lt;element name="sequenceName" type="{http://bioxsd.org/BioXSD-1.1}Name"/>
 *           &lt;sequence>
 *             &lt;element name="species" type="{http://bioxsd.org/BioXSD-1.1}Species"/>
 *             &lt;element name="genomeBuild" type="{http://bioxsd.org/BioXSD-1.1}EntryReference"/>
 *             &lt;element name="chromosome" type="{http://bioxsd.org/BioXSD-1.1}ChromosomeName"/>
 *             &lt;element name="subsequencePosition" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *             &lt;element name="variantAccession" type="{http://bioxsd.org/BioXSD-1.1}Accession" minOccurs="0"/>
 *             &lt;element name="variantNote" type="{http://bioxsd.org/BioXSD-1.1}Name" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="gap" type="{http://bioxsd.org/BioXSD-1.1}Gap" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="insert" type="{http://bioxsd.org/BioXSD-1.1}Insert" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="frameshift" type="{http://bioxsd.org/BioXSD-1.1}Frameshift" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reversedDirection" type="{http://bioxsd.org/BioXSD-1.1}Flag" minOccurs="0"/>
 *         &lt;element name="sequenceScore" type="{http://bioxsd.org/BioXSD-1.1}Result" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlignedBiosequence", propOrder = {
    "localAlignmentPosition",
    "sequenceRecord",
    "sequenceReference",
    "sequenceName",
    "species",
    "genomeBuild",
    "chromosome",
    "subsequencePosition",
    "variantAccession",
    "variantNote",
    "gap",
    "insert",
    "frameshift",
    "reversedDirection",
    "sequenceScore"
})
@XmlSeeAlso({
    AlignedGeneralNucleotideSequence.class,
    AlignedGeneralAminoacidSequence.class
})
public class AlignedBiosequence {

    protected SequencePosition localAlignmentPosition;
    protected BiosequenceRecord sequenceRecord;
    protected SequenceReference sequenceReference;
    protected String sequenceName;
    protected Species species;
    protected EntryReference genomeBuild;
    protected String chromosome;
    protected SequencePosition subsequencePosition;
    protected String variantAccession;
    protected String variantNote;
    protected List<Gap> gap;
    protected List<Insert> insert;
    protected List<Frameshift> frameshift;
    protected Flag reversedDirection;
    protected List<Result> sequenceScore;

    /**
     * Gets the value of the localAlignmentPosition property.
     * 
     * @return
     *     possible object is
     *     {@link SequencePosition }
     *     
     */
    public SequencePosition getLocalAlignmentPosition() {
        return localAlignmentPosition;
    }

    /**
     * Sets the value of the localAlignmentPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencePosition }
     *     
     */
    public void setLocalAlignmentPosition(SequencePosition value) {
        this.localAlignmentPosition = value;
    }

    /**
     * Gets the value of the sequenceRecord property.
     * 
     * @return
     *     possible object is
     *     {@link BiosequenceRecord }
     *     
     */
    public BiosequenceRecord getSequenceRecord() {
        return sequenceRecord;
    }

    /**
     * Sets the value of the sequenceRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BiosequenceRecord }
     *     
     */
    public void setSequenceRecord(BiosequenceRecord value) {
        this.sequenceRecord = value;
    }

    /**
     * Gets the value of the sequenceReference property.
     * 
     * @return
     *     possible object is
     *     {@link SequenceReference }
     *     
     */
    public SequenceReference getSequenceReference() {
        return sequenceReference;
    }

    /**
     * Sets the value of the sequenceReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequenceReference }
     *     
     */
    public void setSequenceReference(SequenceReference value) {
        this.sequenceReference = value;
    }

    /**
     * Gets the value of the sequenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceName() {
        return sequenceName;
    }

    /**
     * Sets the value of the sequenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceName(String value) {
        this.sequenceName = value;
    }

    /**
     * Gets the value of the species property.
     * 
     * @return
     *     possible object is
     *     {@link Species }
     *     
     */
    public Species getSpecies() {
        return species;
    }

    /**
     * Sets the value of the species property.
     * 
     * @param value
     *     allowed object is
     *     {@link Species }
     *     
     */
    public void setSpecies(Species value) {
        this.species = value;
    }

    /**
     * Gets the value of the genomeBuild property.
     * 
     * @return
     *     possible object is
     *     {@link EntryReference }
     *     
     */
    public EntryReference getGenomeBuild() {
        return genomeBuild;
    }

    /**
     * Sets the value of the genomeBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryReference }
     *     
     */
    public void setGenomeBuild(EntryReference value) {
        this.genomeBuild = value;
    }

    /**
     * Gets the value of the chromosome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChromosome() {
        return chromosome;
    }

    /**
     * Sets the value of the chromosome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChromosome(String value) {
        this.chromosome = value;
    }

    /**
     * Gets the value of the subsequencePosition property.
     * 
     * @return
     *     possible object is
     *     {@link SequencePosition }
     *     
     */
    public SequencePosition getSubsequencePosition() {
        return subsequencePosition;
    }

    /**
     * Sets the value of the subsequencePosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencePosition }
     *     
     */
    public void setSubsequencePosition(SequencePosition value) {
        this.subsequencePosition = value;
    }

    /**
     * Gets the value of the variantAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantAccession() {
        return variantAccession;
    }

    /**
     * Sets the value of the variantAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantAccession(String value) {
        this.variantAccession = value;
    }

    /**
     * Gets the value of the variantNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantNote() {
        return variantNote;
    }

    /**
     * Sets the value of the variantNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantNote(String value) {
        this.variantNote = value;
    }

    /**
     * Gets the value of the gap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gap }
     * 
     * 
     */
    public List<Gap> getGap() {
        if (gap == null) {
            gap = new ArrayList<Gap>();
        }
        return this.gap;
    }

    /**
     * Gets the value of the insert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the insert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInsert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Insert }
     * 
     * 
     */
    public List<Insert> getInsert() {
        if (insert == null) {
            insert = new ArrayList<Insert>();
        }
        return this.insert;
    }

    /**
     * Gets the value of the frameshift property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frameshift property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrameshift().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Frameshift }
     * 
     * 
     */
    public List<Frameshift> getFrameshift() {
        if (frameshift == null) {
            frameshift = new ArrayList<Frameshift>();
        }
        return this.frameshift;
    }

    /**
     * Gets the value of the reversedDirection property.
     * 
     * @return
     *     possible object is
     *     {@link Flag }
     *     
     */
    public Flag getReversedDirection() {
        return reversedDirection;
    }

    /**
     * Sets the value of the reversedDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flag }
     *     
     */
    public void setReversedDirection(Flag value) {
        this.reversedDirection = value;
    }

    /**
     * Gets the value of the sequenceScore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sequenceScore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSequenceScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Result }
     * 
     * 
     */
    public List<Result> getSequenceScore() {
        if (sequenceScore == null) {
            sequenceScore = new ArrayList<Result>();
        }
        return this.sequenceScore;
    }

}
