//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MethodResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MethodResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://bioxsd.org/BioXSD-1.1}Method">
 *                 &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="score" type="{http://bioxsd.org/BioXSD-1.1}Score" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MethodResult", propOrder = {
    "method",
    "score"
})
public class MethodResult {

    @XmlElement(required = true)
    protected MethodResult.Method method;
    protected List<Score> score;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link MethodResult.Method }
     *     
     */
    public MethodResult.Method getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodResult.Method }
     *     
     */
    public void setMethod(MethodResult.Method value) {
        this.method = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the score property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Score }
     * 
     * 
     */
    public List<Score> getScore() {
        if (score == null) {
            score = new ArrayList<Score>();
        }
        return this.score;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}Method">
     *       &lt;attribute name="localId" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Method
        extends ncbiseqout.Method
    {

        @XmlAttribute(name = "localId")
        protected String localId;

        /**
         * Gets the value of the localId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalId() {
            return localId;
        }

        /**
         * Sets the value of the localId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalId(String value) {
            this.localId = value;
        }

    }

}
