//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bioxsd.org/BioXSD-1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ncbiseqout;
