//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecommendedScoreName.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RecommendedScoreName">
 *   &lt;restriction base="{http://bioxsd.org/BioXSD-1.1}Name">
 *     &lt;enumeration value="p-value"/>
 *     &lt;enumeration value="E-value"/>
 *     &lt;enumeration value="Standard deviation"/>
 *     &lt;enumeration value="Bit"/>
 *     &lt;enumeration value="Z-score"/>
 *     &lt;enumeration value="Probability"/>
 *     &lt;enumeration value="Q3"/>
 *     &lt;enumeration value="SOV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RecommendedScoreName")
@XmlEnum
public enum RecommendedScoreName {

    @XmlEnumValue("p-value")
    P_VALUE("p-value"),
    @XmlEnumValue("E-value")
    E_VALUE("E-value"),
    @XmlEnumValue("Standard deviation")
    STANDARD_DEVIATION("Standard deviation"),
    @XmlEnumValue("Bit")
    BIT("Bit"),
    @XmlEnumValue("Z-score")
    Z_SCORE("Z-score"),
    @XmlEnumValue("Probability")
    PROBABILITY("Probability"),
    @XmlEnumValue("Q3")
    Q_3("Q3"),
    SOV("SOV");
    private final String value;

    RecommendedScoreName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RecommendedScoreName fromValue(String v) {
        for (RecommendedScoreName c: RecommendedScoreName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
