//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Score of an experiment or computation
 * 
 * <p>Java class for Score complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Score">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}ScoreType">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://bioxsd.org/BioXSD-1.1}SequencePosition" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" use="required" type="{http://bioxsd.org/BioXSD-1.1}ScoreValue" />
 *       &lt;attribute name="scoreTypeIdRef" type="{http://bioxsd.org/BioXSD-1.1}LocalId" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Score", propOrder = {
    "position"
})
public class Score
    extends ScoreType
{

    protected SequencePosition position;
    @XmlAttribute(name = "value", required = true)
    protected String value;
    @XmlAttribute(name = "scoreTypeIdRef")
    protected String scoreTypeIdRef;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link SequencePosition }
     *     
     */
    public SequencePosition getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencePosition }
     *     
     */
    public void setPosition(SequencePosition value) {
        this.position = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the scoreTypeIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoreTypeIdRef() {
        return scoreTypeIdRef;
    }

    /**
     * Sets the value of the scoreTypeIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoreTypeIdRef(String value) {
        this.scoreTypeIdRef = value;
    }

}
