//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference to a concept from an ontology or the Semantic Web, or a term from a controlled vocabulary
 * 
 * <p>Java class for SemanticConcept complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SemanticConcept">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}OntologyReference">
 *       &lt;attribute name="accession" type="{http://bioxsd.org/BioXSD-1.1}Accession" />
 *       &lt;attribute name="conceptUri" type="{http://bioxsd.org/BioXSD-1.1}Uri" />
 *       &lt;attribute name="term" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SemanticConcept")
@XmlSeeAlso({
    ncbiseqout.FeatureRecord.BlockWithOccurrenceReferences.SemanticConcept.class
})
public class SemanticConcept
    extends OntologyReference
{

    @XmlAttribute(name = "accession")
    protected String accession;
    @XmlAttribute(name = "conceptUri")
    protected String conceptUri;
    @XmlAttribute(name = "term")
    protected String term;

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccession() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccession(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the conceptUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConceptUri() {
        return conceptUri;
    }

    /**
     * Sets the value of the conceptUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConceptUri(String value) {
        this.conceptUri = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

}
