//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 11:32:28 PM CEST 
//


package ncbiseqout;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference to a species (can be used also for a phenotype, cell line, tissue, sample, geo location, ...)
 * 
 * <p>Java class for Species complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Species">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bioxsd.org/BioXSD-1.1}EntryReference">
 *       &lt;attribute name="speciesName" type="{http://bioxsd.org/BioXSD-1.1}Name" />
 *       &lt;attribute name="speciesNote" type="{http://bioxsd.org/BioXSD-1.1}Text" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Species")
public class Species
    extends EntryReference
{

    @XmlAttribute(name = "speciesName")
    protected String speciesName;
    @XmlAttribute(name = "speciesNote")
    protected String speciesNote;

    /**
     * Gets the value of the speciesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * Sets the value of the speciesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesName(String value) {
        this.speciesName = value;
    }

    /**
     * Gets the value of the speciesNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeciesNote() {
        return speciesNote;
    }

    /**
     * Sets the value of the speciesNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeciesNote(String value) {
        this.speciesNote = value;
    }

}
